#!/bin/bash
set -ex

# update app users and set permissions
FLUSH PRIVILEGES;

CREATE USER 'webapp'@'%' IDENTIFIED WITH mysql_native_password BY '@@{MySqlPassword}@@' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT, INSERT ON *.* TO 'webapp'@'%';
FLUSH PRIVILEGES;

CREATE USER 'webapp'@'localhost' IDENTIFIED WITH mysql_native_password BY '@@{MySqlPassword}@@' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT, INSERT ON *.* TO 'webapp'@'localhost';
FLUSH PRIVILEGES;

EOF
